version: '2'
services:
    lab1-app:
        image: lab1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lab1-mysql:3306/lab1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lab1-mysql:
        extends:
            file: mysql.yml
            service: lab1-mysql
